quarkus.http.port=8080

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./db/h2-data/orders-db
quarkus.datasource.username=sa
quarkus.datasource.password=sa

quarkus.hibernate-orm.schema-management.strategy=none

quarkus.hibernate-orm.log.sql=true

quarkus.liquibase.migrate-at-start=true

quarkus.log.category."io.smallrye.jwt".level=DEBUG
#smallrye.jwt.new-token.signature-algorithm=HS256
#mp.jwt.verify.secret=a-string-secret-at-least-256-bits-long
mp.jwt.verify.issuer=https://example.com/issuer
mp.jwt.verify.publickey.location=publicKey.pem

# mp.messaging.outgoing.orders.connector=smallrye-amqp
#mp.messaging.outgoing.orders.address=orders
#mp.messaging.outgoing.orders.serializer=smallrye.jsonb

#amqp-host=localhost
#amqp-port=5672
