quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/h2/orders-db;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=sa

# Konfigurationseintrag hat sich geändert
# alt
# quarkus.hibernate-orm.database.generation=update

# neu
quarkus.hibernate-orm.schema-management.strategy=update
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.hibernate-orm.log.sql=true
